export const apple = [
    {  
        "title": "A. VORSTELLUNG UNSERER DIENSTE",
        "content":"Diese Vereinbarung regelt Ihre Nutzung der Apple-Dienste einschließlich, sofern verfügbar, App Store, Apple Arcade, Apple Books, Apple Fitness+, Apple Music, Apple News, Apple News+, Apple One, Apple Podcasts, Apple Podcasts Subscriptions, Apple TV, Apple TV+, Apple TV Channels, Game Center und iTunes („Dienste“), über welche Sie Inhalte, Apps (wie nachstehend definiert) und sonstige In-App-Dienste („Inhalte“) kaufen, beziehen, lizensieren, leihen oder abonnieren können. Inhalte können über die Dienste von Apple oder einem Dritten angeboten werden, und in beiden Fällen sind Sie durch das geltende Verbraucherrecht geschützt. Unsere Dienste stehen Ihnen in Ihrem Land oder Wohnsitz („Heimatland“) sowie in allen anderen EU-Ländern, in denen Sie sich vorübergehend aufhalten, für Ihre Nutzung zur Verfügung. Durch Einrichtung eines Accounts zur Nutzung der Dienste in einem bestimmten Land oder Gebiet legen Sie es als ihr Heimatland fest. Zur Nutzung unserer Dienste benötigen Sie kompatible Hardware, Software (letzte Version empfohlen und ggf. erforderlich) und Internetzugang (Gebühren können anfallen). Die Funktionalität unserer Dienste kann von diesen Faktoren beeinflusst werden."
    },
    {
    "title": "B. NUTZUNG UNSERER DIENSTE",
    "content": [ 
        {
            "title": "ZAHLUNGEN, STEUERN UND ERSTATTUNGEN",
            "content": "Sie können Inhalte kostenlos oder kostenpflichtig über unsere Dienste erwerben, wobei beides als eine „Transaktion“ bezeichnet wird. Mit jeder Transaktion erwerben Sie nur eine Lizenz zur Nutzung der Inhalte. Jede Transaktion ist ein elektronischer Vertrag zwischen Ihnen und Apple und/oder zwischen Ihnen und dem Unternehmen, das die Inhalte über unsere Dienste zur Verfügung stellt. Wenn Sie jedoch ein Kunde von Apple Distribution International Ltd. sind, ist Apple Distribution International Ltd. der Vertragspartner für Inhalte, die Sie von Apple Books, Apple Podcasts oder App Store, wie auf der Produktseite und/oder während des Erwerbsvorgangs für den relevanten Dienst angezeigt, erwerben. In einem solchen Fall erwerben Sie die Inhalte von Apple Distribution International Ltd., die vom Provider der Inhalte (z. B. App-Provider (wie nachstehend definiert), Buchverleger usw.) lizenziert werden. Wenn Sie Ihre erste Transaktion vornehmen, werden wir Sie auffordern zu wählen, wie häufig wir bei künftigen Transaktionen die Angabe Ihres Passworts verlangen sollen. Auf entsprechender Apple-Hardware, wenn Sie bei Transaktionen Touch ID aktivieren, werden wir Sie auffordern, alle Transaktionen mit Ihrem Fingerabdruck zu authentifizieren. Wenn Sie für Ihre Transaktionen Face ID aktivieren, nutzen wir Gesichtserkennung für die Authentifizierung aller Transaktionen. Verwalten Sie Ihre Passwort-Einstellungen jederzeit gemäß der folgenden Anleitung: https://support.apple.com/HT204030. Apple belastet Ihre gewählte Zahlungsmethode für kostenpflichtige Transaktionen, einschließlich anfallender Steuern. Falls Sie Ihre Zahlungsmethode auch der Apple Wallet hinzugefügt haben, kann Apple Ihre gewählte Zahlungsmethode in der Apple Wallet mit Hilfe von Apple Pay belasten. Sie können mehrere Zahlungsmethoden mit Ihrer Apple-ID verbinden, und Sie stimmen zu, dass Apple die Zahlungsarten für Transaktionen speichern und verwenden kann. Ihre primäre Zahlungsmethode wird oben auf der Zahlungsseite Ihrer Kontoeinstellungen angezeigt."
                    + "Wenn Ihre primäre Zahlungsmethode aus irgendeinem Grund nicht belastet werden kann (zum Beispiel, weil sie abgelaufen oder die Deckung unzureichend ist), erlauben Sie Apple zu versuchen, Ihre anderen gültigen Zahlungsmethoden von oben bis unten zu verwenden, in der Reihenfolge, in der sie auf der Zahlungsseite Ihrer Kontoeinstellungen erscheinen. Falls es uns nicht gelingt eine gültige Zahlungsmethode zu belasten, bleiben Sie für alle ausstehenden Beträge verantwortlich und wir können versuchen den fälligen Betrag erneut einzuziehen oder eine andere Zahlungsmethode anzufordern. Wenn Sie Inhalte vorbestellen, werden Ihnen diese berechnet, sobald die Inhalte an Sie geliefert werden (soweit Sie nicht vor der Bereitstellung der Inhalte stornieren). In Übereinstimmung mit örtlich geltendem Recht kann Apple die Informationen zu Ihren Zahlungsmethoden automatisch aktualisieren, falls solche Informationen von Ihren Zahlungsnetzwerken oder Finanzinstituten bereitgestellt werden. Die Bedingungen für Gutscheine und Geschenkkarten/-codes finden Sie hier: https://www.apple.com/legal/internet-services/itunes/giftcards/. Für Details, wie Transaktionen abgerechnet werden, besuchen Sie bitte https://support.apple.com/HT201359. Sie erklären sich damit einverstanden, alle Rechnungen in elektronischer Form zu erhalten, einschließlich E-Mail . Preise für Inhalte können jederzeit geändert werden. Wenn technische Probleme die Lieferung von Inhalten verhindern oder unverhältnismäßig verzögern, können Sie als einziges Rechtsmittel entweder eine erneute Zustellung der Inhalte (falls möglich) oder eine Erstattung des gezahlten Preises verlangen. Apple kann Zahlungen aussetzen oder aufheben oder ein Erstattungsverlangen ablehnen, wenn wir Hinweise auf Betrug, Missbrauch, illegales oder ein sonstiges manipulatives Verhalten, das Apple zu einer entsprechenden Gegenforderung berechtigt, feststellen."
                    + "Widerrufsrecht: Wenn Sie Ihre Bestellung rückgängig machen möchten, können Sie sie binnen 14 Tagen nachdem Sie die Rechnung erhalten haben ohne Angabe von Gründen widerrufen."
                    + "Um Ihre Bestellung rückgängig zu machen, müssen Sie uns über Ihre Entscheidung informieren. Um die unverzügliche Bearbeitung sicherzustellen, empfehlen wir Ihnen für die Stornierung von sämtlichen Artikeln, „Problem melden” zu nutzen. Dies gilt nicht für „Staffel vervollständigen“, das rückgängig gemacht werden kann, indem der iTunes Support kontaktiert wird. Abonnementdienste können nur nach dem ersten Abschluss storniert werden. Sie haben ebenfalls das Recht, uns über Ihren Entschluss eine Bestellung zu stornieren zu informieren, indem Sie das nachfolgende Muster-Widerrufsformular verwenden oder eine andere eindeutige Erklärung abgeben. Wenn Sie „Problem melden” nutzen, werden wir Ihnen unverzüglich eine Bestätigung über den Eingang Ihrer Stornierung übermitteln."
                    + "Zur Einhaltung der Widerrufsfrist müssen Sie die Mitteilung über die Stornierung der Bestellung vor Ablauf der 14-Tage-Frist absenden."
                    + "Folgen des Widerrufs: Wir werden Ihnen die Zahlung innerhalb von 14 Tagen nach Erhalt Ihrer Widerrufsmitteilung zurückerstatten. Für die Rückzahlung verwenden wir dieselbe Zahlungsmethode, die Sie bei der Transaktion eingesetzt haben, und werden Ihnen hierfür keine Entgelte berechnen."
                    + "Ausnahme zum Widerrufsrecht: Sie können eine Bestellung für Inhalte nicht widerrufen, wenn die Lieferung mit Ihrer ausdrücklichen Zustimmung und Ihrer Kenntnisnahme, dass Sie dadurch Ihr Widerrufsrecht verlieren, begonnen hat."
                    + "Muster-Widerrufsformular:" 
                    + "- An Apple Distribution International Ltd., iTunes Store Customer Support, Hollyhill Industrial Estate, Hollyhill, Cork, Republic of Ireland, rightofwithdrawal@apple.com:"
                    + "- Hiermit widerrufe ich den von mir abgeschlossenen Vertrag für: [BESTELLNUMMER, ARTIKEL, INTERPRET:IN UND ART EINFÜGEN]"
                    + "- Bestellt am [DATUM EINFÜGEN] / erhalten am [DATUM EINFÜGEN]"
                    + "- Name des:der Verbraucher:in"
                    + "- Anschrift des:der Verbraucher:in"
                    + "- E-Mail-Adresse des:der Verbraucher:in"
                    + "- Datum"
        },
        {
            "title": "ACCOUNT",
            "content": "Die Nutzung unserer Dienste und der Zugriff auf Ihre Inhalte können eine Apple-ID erfordern. Eine Apple-ID ist der Account, den Sie über das gesamte Ökosystem von Apple nutzen. Die Nutzung des Game Centers unterliegt dieser Vereinbarung und erfordert ebenfalls einen Game Center-Account. Ihr Account ist wertvoll und Sie sind verantwortlich für die Aufrechterhaltung seiner Vertraulichkeit und Sicherheit. Apple ist nicht verantwortlich für Verluste, die durch die unbefugte Nutzung Ihres Accounts entstehen. Bitten wenden Sie sich an Apple, wenn Sie vermuten, dass Ihr Account kompromittiert wurde."
                    + "Sie müssen mindestens 13 Jahre alt sein (oder ein entsprechendes Mindestalter in Ihrem Heimatland, wie bei der Erstellung der Apple ID angegeben, haben), um einen Account zu erstellen und unsere Dienste zu nutzen. Apple-IDs können für Personen, die dieses Alter noch nicht erreicht haben, von einem Elternteil oder einem:einer Erziehungsberechtigten über die Funktion „Familienfreigabe“ oder von einer anerkannten Bildungseinrichtung erstellt werden. Ein Elternteil oder ein:e Erziehungsberechtigte:r, der:die ein Konto für sein:ihr minderjähriges Kind erstellt, muss diese Vereinbarung zusammen mit dem:r Minderjährigen durchsehen, um sicherzustellen, dass beide ihren Inhalt verstehen."
                    + "Sie haben das Recht, einen Nachlasskontakt für Ihre Apple‑ID hinzuzufügen, zu benachrichtigen oder zu entfernen, wie auf der Seite http://support.apple.com/HT212360 beschrieben ist. Der Zugang des Nachlasskontakts zu Ihrer Apple‑ID ist eingeschränkt, wie auf der Seite http://support.apple.com/HT212361 beschrieben ist."
        },
        {
            "title": "DATENSCHUTZ",
            "content": "Ihre Nutzung unserer Dienste unterliegt der Apple Datenschutzrichtlinie, die unter https://www.apple.com/legal/privacy/ zur Verfügung steht."
        },
        {
            "title": "REGELN FÜR DIE NUTZUNG DER DIENSTE UND INHALTE",
            "content": "Ihre Nutzung der Dienste und Inhalte muss den in diesem Abschnitt angegebenen Regeln folgen („Nutzungsregeln“). Jede sonstige Nutzung der Dienste und Inhalte stellt einen wesentlichen Verstoß gegen diese Vereinbarung dar. Apple kann Ihre Nutzung der Dienste und Inhalte überwachen, um sicherzustellen, dass Sie diese Nutzungsregeln befolgen."
                    + "Alle Dienste:"
                    + "- Sie dürfen die Dienste und Inhalte nur für private, nicht-kommerzielle Zwecke nutzen (außer soweit im nachstehenden Abschnitt „Inhalte des App Store“ angegeben bzw. wie anderweitig von Apple festgelegt)."
                    + "- Die Bereitstellung von Diensten oder Inhalten durch Apple räumt Ihnen keine Rechte zur kommerziellen oder werbemäßigen Nutzung ein, und stellt keine Gewährung von Rechten oder einen Verzicht auf Rechte durch die Urheberrechtsinhaber:innen dar."
                    + "- Sie können Inhalte von bis zu fünf verschiedenen Apple-IDs auf jedem Gerät nutzen."
                    + "- Für alle Dienste können Sie sich mit bis zu 10 Geräten (aber höchstens 5 Computern) gleichzeitig mit Ihrer Apple-ID anmelden, wenngleich simultane Streams oder Downloads von Inhalten auf eine geringere Anzahl an Geräten begrenzt sein kann, wie nachstehend unter „Apple Music“ und „Inhalte von Apple TV“ dargelegt. Jeder Computer muss auch unter Verwendung derselben Apple‑ID autorisiert werden (mehr über die Autorisierung von Computern erfahren Sie unter https://support.apple.com/HT201251). Geräte können einmal alle 90 Tage mit einer anderen Apple‑ID verbunden werden."
                    + "- Das Manipulieren von Abspielzahlen, Downloads, Bewertungen oder Reviews über beliebige Mittel wie zum Beispiel (i) unter Verwendung eines Bots, Scripts oder automatisierten Prozesses; oder (ii) durch Bereitstellung oder Annahme jeglicher Art von Kompensation oder Anreiz ist verboten."
                    + "- Es liegt in Ihrer Verantwortung, Inhalte nicht zu verlieren, zu zerstören oder zu beschädigen, sobald Sie diese heruntergeladen haben. Wir empfehlen, regelmäßig Sicherungskopien von Ihren Inhalten zu erstellen."
                    + "- Es ist Ihnen nicht gestattet, die in den Diensten oder Inhalten enthaltenen Sicherheitstechnologien zu manipulieren oder zu umgehen."
                    + "- Sie dürfen nur mit der Software von Apple auf unsere Dienste zugreifen und diese Software nicht modifizieren oder modifizierte Versionen dieser Software verwenden."
                    + "- Sie können die Produktseite für jeden Dienst oder jede Drittanbieter-App im App Store konsultieren, um die Kompatibilität festzustellen."
                    + "- Video-Inhalte erfordern einen HDCP-Anschluss."
                    + "Gekaufte und geliehene Audio- und Video-Inhalte:"
                    + "- Sie können DRM (Digital Rights Management)-freie Inhalte auf einer angemessenen Anzahl von kompatiblen Geräten nutzen, die sich in Ihrem Eigentum oder Besitz befinden. DRM-geschützte Inhalte können auf bis zu fünf Computern und einer beliebigen Zahl von Geräten, welche Sie mit diesen Computern synchronisieren, genutzt werden."
                    + "- Geliehene Inhaltekönnen jeweils nur auf einem einzigen Gerät angezeigt werden, müssen innerhalb von 30 Tagen abgespielt und innerhalb von 48 Stunden nach Abspielstart beendet werden (Anhalten, Pausieren oder Neustarten verlängert diesen Zeitraum nicht)."
                    + "- Sie können eine Audio-Playlist gekaufter Musik bis zu sieben Mal zum Zweck des Anhörens auf CD brennen; diese Begrenzung gilt nicht für DRM-freie Inhalte. Andere Inhalte dürfen nicht auf CD gebrannt werden. Im Rahmen von lokalen, das Urheberrecht schützenden Gesetzen dürfen Sie Ihre CD, auf die Sie die Inhalte gebrannt haben, ebenso verwenden, als ob es eine CD wäre, die Sie in einem Einzelhandelsgeschäft erworben haben."
                    + "- Gekaufte Inhalte bleiben in der Regel für Sie zum Herunterladen, erneuten Herunterladen oder anderweitigen Zugriff von Apple verfügbar. Auch wenn es unwahrscheinlich ist, kann es vorkommen, dass Inhalte nach Ihrem Kauf aus den Diensten entfernt werden (z. B. weil der Provider sie entfernt hat), und nicht mehr zum weiteren Herunterladen oder Zugang von Apple zur Verfügung stehen. Um sicherzustellen, dass Sie die Inhalte weiter verwenden können, empfehlen wir Ihnen alle gekauften Inhalte auf eines Ihrer Geräte herunterzuladen und eine Sicherheitskopie zu machen."
                    + "Inhalte des App Store:"
                    + "- Der Begriff „Apps“ umfasst Apps und App-Clips für eine beliebige Apple-Plattform und/oder ein beliebiges Apple Betriebssystem, darunter In-App-Käufe, Extensions (wie Tastaturen), Sticker und Abonnements, die in solchen Apps oder App-Clips zur Verfügung gestellt werden."
                    + "- Natürliche Personen, die im Namen eines Handelsunternehmens, einer staatlichen Organisation oder einer Bildungseinrichtung (ein „Unternehmen“) handeln, können Apps mit Ausnahme von Arcade-Apps zur Nutzung durch entweder (i) eine Einzelperson auf einem oder mehreren Geräten, die sich im Eigentum oder Besitz eines Unternehmens befinden, oder (ii) eine Vielzahl von Einzelpersonen auf einem einzigen gemeinsam genutzten Gerät, das sich im Eigentum oder Besitz eines Unternehmens befindet, herunterladen und synchronisieren. Zur Klarstellung sei angemerkt, dass für jedes Gerät, das nacheinander oder gemeinsam von einer Vielzahl von Benutzer:innen genutzt wird, eine gesonderte Lizenz erforderlich ist."
                    + "Apple Music:"
                    + "- Eine Apple Music-Einzelmitgliedschaft ermöglicht Ihnen das Streaming auf jeweils nur einem Gerät ; eine Familienmitgliedschaft ermöglicht Ihnen oder Ihren Familienmitgliedern das Streaming auf bis zu sechs Geräten gleichzeitig."
                    + "Apple Arcade:"
                    + "- Apple Arcade-Apps können nur mit einem gültigen Apple Arcade-Probezugang oder -Abonnement heruntergeladen bzw. erneut heruntergeladen werden."
                    + "- Endet Ihr Abonnement, stehen Ihnen über Apple Arcade heruntergeladene Apps nicht mehr zur Verfügung."
                    + "Inhalte von Apple TV:"
                    + "- Bei den meisten Kanälen können Sie Videoinhalte auf bis zu drei Geräten gleichzeitig streamen."
                    + "- Mehr zu den Nutzungsbedingungen der Inhalte von Apple TV erfahren Sie unter https://support.apple.com/HT210074."
        },
        {
            "title": "DOWNLOADS",
            "content": "Die Anzahl an Inhalten, die Sie herunterladen können, kann begrenzt sein und einige heruntergeladene Inhalte können nach einer bestimmten Zeit nach dem Herunterladen oder dem ersten Abspielen verfallen. Bestimmte Inhalte können ggf. gar nicht heruntergeladen werden."
                    + "Sie haben ggf. die Möglichkeit, bereits erworbene Inhalte auf Ihre Geräte, die mit derselben Apple-ID registriert sind („verknüpfte Geräte“), erneut herunterzuladen („erneute Downloads“). Sie finden die Inhaltstypen, die in Ihrem Heimatland zum erneuten Download zur Verfügung stehen, unter https://support.apple.com/HT204632. Inhalte stehen ggf. nicht für erneute Downloads zur Verfügung, wenn sie nicht mehr über unsere Dienste angeboten werden."
                    + "Inhalte können auch jederzeit aus unseren Diensten entfernt werden (z. B. weil der Anbieter sie entfernt hat), woraufhin sie nicht mehr heruntergeladen, erneut heruntergeladen oder anderweitig von Apple abgerufen werden können."
        },   
        {
            "title": "ABONNEMENTS",
            "content": "Die Dienste und bestimmte Apps können es Ihnen ermöglichen, den Zugang zu Inhalten oder Diensten auf Abonnementbasis zu erwerben (\„kostenpflichtige Abonnements\"). Kostenpflichtige Abonnements laufen weiter und werden regelmäßig in Rechnung gestellt, bis sie gekündigt werden. Sie können kostenpflichtige Abonnements mit Wirkung zum Ende des aktuellen Abrechnungszeitraums im Abschnitt \„Abonnements verwalten\" in Ihren Account-Einstellungen kündigen. Information zur Kündigung Ihrer Abonnements finden Sie unter https://support.apple.com/HT202039. Außerdem haben Sie das Recht, kostenpflichtige Abonnements jederzeit mit sofortiger Wirkung zu kündigen und eine anteilige Rückerstattung zu erhalten."
                    + "Wenden Sie sich dazu an den Apple Support unter https://www.apple.com/emea/support/itunes/contact.html oder senden Sie eine E-Mail an Apple Distribution International Limited mit Sitz in Hollyhill Industrial Estate, Hollyhill, Cork, Republic of Ireland. Wenn Ihr Heimatland Deutschland ist, können Sie auch die Nummer 0800 6645 451 anrufen. Sie werden benachrichtigt, wenn sich der Preis für ein kostenpflichtiges Abonnement erhöht und ggf. ist Ihre Zustimmung erforderlich, um das Abonnement fortzusetzen. Sollten die Kosten für die Lizenzierung von Inhalten im Zusammenhang mit einem kostenpflichtigen Abonnement, das von Apple als Provider der Inhalte angeboten wird (ein \„kostenpflichtiges Abonnement von Apple\“) steigen, können wir den Abonnementpreis proportional erhöhen, wobei wir jede ausgleichende Senkung der anderen Kostenelemente bei der Bereitstellung dieses kostenpflichtigen Abonnements von Apple berücksichtigen; wenn sich der Preis eines kostenpflichtigen Abonnements von Apple erhöht werden wir Sie informieren. Die Kosten werden Ihnen spätestens 24 Stunden vor Beginn des nächsten Abrechnungszeitraums berechnet. Falls wir Ihre Zahlungsmethode aus irgendeinem Grund nicht belasten können (z. B. weil sie abgelaufen oder unzureichend gedeckt ist) und Sie das kostenpflichtige Abonnement nicht gekündigt haben, haften Sie für nicht entrichtete Beträge und wir werden versuchen, Ihre Zahlungsmethode zu belasten, sobald Sie Ihre Informationen zur Zahlungsmethode ändern. Dies kann zu einer Änderung des Beginns Ihres nächsten kostenpflichtigen Abonnementzeitraums führen und das Datum ändern, an dem Sie für jeden Zeitraum abgerechnet werden, wie auf Ihrer Quittung angezeigt. Wir behalten uns das Recht vor, Ihr kostenpflichtiges Abonnement zu stornieren, wenn wir Ihre Zahlungsmethode nicht erfolgreich belasten können, um Ihr Abonnement fortzusetzen. Bestimmte kostenpflichtige Abonnements können vor Belastung Ihres Zahlungsmethode eine kostenlose Probenutzung anbieten. Wenn Sie sich entscheiden, ein kostenpflichtiges Abonnementzu kündigen, bevor wir Ihre Zahlungsmethode belasten, kündigen Sie das Abonnement mindestens 24 Stunden vor Ablauf der kostenlosen Probenutzung."
                    + "Wenn Sie eine kostenlose Probenutzung für ein kostenpflichtiges Abonnement von Apple beginnen und sie vor deren Ablauf kündigen, können Sie die kostenlose Probenutzung nicht erneut aktivieren."
                    + "Kostenlose Probenutzungen oder kostenlose Angebote für kostenpflichtige Abonnements von Apple, mit Ausnahme von iCloud+, können nicht mit kostenlosen Probenutzungen oder Angeboten von Apple One kombiniert werden. Wenn Sie eine kostenlose Probenutzung oder ein kostenloses Angebot für ein kostenpflichtiges Abonnement von Apple nutzen und Apple One abonnieren, wird Ihre kostenlose Probenutzung oder Ihr kostenloses Angebot nicht pausiert, auch wenn Sie durch Ihr Abonnement von Apple One Zugriff auf diese kostenpflichtigen Abonnements von Apple haben. Sie erkennen an, dass Ihre kostenlose Probenutzung oder Ihr kostenloses Angebot ablaufen kann, während Sie ein:e zahlende:r Abonnent:in von Apple One sind, und Apple nicht verpflichtet ist, beliebige Teile einer solchen abgelaufenen kostenlosen Probenutzung oder eines solchen abgelaufenen kostenlosen Angebots wiederherzustellen oder Sie dafür zu entschädigen oder anderweitige Kompensationen zu leisten. Wenn Ihr kostenpflichtiges Abonnement eines Dienstes oder von Inhalten endet, verlieren Sie den Zugriff auf jegliche Funktionen oder Inhalte dieses Dienstes, die ein kostenpflichtiges Abonnement erfordern."
        },
        {
            "title": "VERFÜGBARKEIT DER INHALTE UND DIENSTE",
            "content": "In dieser Vereinbarung enthaltene Bedingungen, die sich auf in Ihrem Heimatland nicht zur Verfügung stehende Dienste, Inhaltstypen, Features oder Funktionalitäten beziehen, gelten für Sie nicht bis dieseIhnen zur Verfügung gestellt werden. Um die Inhaltstypen zu sehen, die in Ihrem Heimatland zur Verfügung stehen, gehen Sie zu den Diensten oder besuchen Sie https://support.apple.com/HT204411. Bestimmte Dienste und Inhalte, die Ihnen in Ihrem Heimatland zur Verfügung stehen, sind eventuell nicht verfügbar, wenn Sie ins Ausland reisen, ausgenommen in den Fällen, in denen es gesetzlich vorgeschrieben ist."
        },
        {
            "title": "GERÄTE UND AUSRÜSTUNG VON DRITTPARTEIEN",
            "content": "Möglicherweise können Sie die Dienste oder bestimmte Funktionen der Dienste nicht nutzen, wenn Sie mit einem nicht von Apple stammenden Gerät darauf zugreifen. Bitte konsultieren Sie den App-Store auf Ihrem Fremdgerät, um festzustellen, ob der Dienst unterstützt wird. Zusätzlich können bestimmte Dienste unter bestimmten Umständen und/oder für bestimmte Aktivitäten die Nutzung von Ausrüstung von Drittparteien erfordern, Sie dazu auffordern oder deren Nutzung vorschlagen. Eine solche Nutzung unterliegt den Bedingungen dieser Ausrüstung und hat gemäß den geltenden Anweisungen des Herstellers zu erfolgen. Mit der Nutzung der Dienste erklären Sie sich einverstanden, dass Apple kleine Updates seiner Software auf die Geräte von den Drittherstellern laden und installieren kann."
        },
        {
            "title": "KUNDENSUPPORT",
            "content": "Wenn Sie Fragen zu unseren Diensten haben, z. B. zur Rechnungsstellung, zu Abonnements oder zu Ihrer Apple ID, besuchen Sie bitte https://getsupport.apple.com. Dort können Sie sich per Telefon, E-Mail oder Chat mit uns in Verbindung setzen, nachdem Sie das für Sie relevante Thema ausgewählt haben. Wenn Sie sich dafür entscheiden mit uns zu chatten, haben Sie die Möglichkeit, eine Abschrift Ihres Gesprächs herunterzuladen, die auch das Datum und die Uhrzeit enthält, zu der das Gespräch stattgefunden hat."
                    + "Wir bieten allgemeinen Support für alle Dienste mit Ausnahme des App Store, für den Folgendes gilt: Apple bietet Support für alle Angelegenheiten im Zusammenhang mit der Transaktion, einschließlich, aber nicht beschränkt auf Zahlung, Lieferung und Rückerstattung; für alle Angelegenheiten im Zusammenhang mit dem Inhalt und der Funktionalität einer App wenden Sie sich bitte an den App-Provider (wie auf der Produktseite der App im App Store angezeigt)."
        }
        ]
    },
    {
        "title": "C. IHRE BEITRÄGE ZU UNSEREN DIENSTEN",
        "content": "Unsere Dienste können es Ihnen ermöglichen, Materialien wie etwa Kommentare, Bewertungen und Rezensionen, Bilder, Videos und Podcasts (einschließlich damit verbundener Metadaten und Illustrationen) einzureichen oder zu posten. Ihre Nutzung dieser Funktionen muss den nachstehenden Richtlinien für Beiträge entsprechen, die von Zeit zu Zeit aktualisiert werden können. Wenn wir Kenntnis von Materialien erhalten, die gegen unsere Richtlinien für Beiträge verstoßen, werden wir solche Materialien entfernen. Wenn Sie Materialien entdecken, die nicht den Richtlinien für Beiträge entsprechen, nutzen Sie bitte die Funktion „Ein Problem melden“. Soweit dies nicht gesetzlich verboten ist, gewähren Sie Apple hiermit eine weltweite, gebührenfreie, nicht exklusive Lizenz zur Nutzung der von Ihnen eingereichten Materialien innerhalb der Dienste und des damit verbundenen Marketings sowie zur Nutzung der von Ihnen eingereichten Materialien für Apple-interne Zwecke. Apple kann das eingereichte Material überwachen und entscheiden, es zu entfernen oder zu bearbeiten. Apple überwacht oder prüft nicht, ob Sie einen Dienst genutzt oder Inhalte konsumiert haben, bevor Sie einen Kommentar, eine Bewertung oder eine Rezension zu diesem Dienst oder Inhalt abgeben."
                    + "Richtlinien für Beiträge: Sie dürfen die Dienste nicht nutzen, um:"
                    + "- Materialien einzustellen, (i) für die Sie keine Erlaubnis, kein Recht oder keine Lizenz zur Nutzung haben, oder (ii) die die Rechte einer Drittpartei verletzen;"
                    + "- kontroverse, anstößige, illegale, irreführende, unrichtige oder schädliche Inhalte einzustellen;"
                    + "- personenbezogene, private oder vertrauliche Informationen einzustellen, die anderen gehören;"
                    + "- personenbezogene Informationen von Minderjährigen zu verlangen;"
                    + "- sich als jemand anderes auszugeben oder Ihre Verbindung zu einer anderen natürlichen oder juristischen Person falsch darzustellen;"
                    + "- Spam einzustellen oder zu übermitteln, insbesondere unerwünschte oder unbefugte Werbung, Werbematerialien oder informationelle Ankündigungen;"
                    + "- eine Bewertung oder eine Rezension im Austausch für jegliche Art von Kompensation oder Anreiz zu posten, zu modifizieren oder zu entfernen;"
                    + "- eine falsche, missbräuchliche, schädliche, irreführende böswilligeoder für den betreffenden Inhalt irrelevante Bewertung oder Rezension zu posten;"
                    + "- illegale, betrügerische oder manipulative Aktivitäten zu planen oder durchzuführen."
    },
    {
        "title": "D. FAMILIENFREIGABE",
        "content": "Der:Die Organisator:in einer Familie („Organisator:in“) muss 18 Jahre (oder das entsprechende Alter der Volljährigkeit in Ihrem Heimatland) oder älter sein und ein Elternteil oder ein:e Erziehungsberechtigte:r aller Familienmitglieder sein, die unter 13 Jahre (oder dem entsprechenden Mindestalter in deren Heimatland wie im Registrierungsverfahren angegeben) sind. Apple-Geräte werden für den Zugriff auf alle Familienfreigabe-Funktionen benötigt. Mit Familenfreigabe können entsprechende Abonnements von bis zu sechs Mitgliedern einer Familie gemeinsam genutzt werden. Mehr über die Familienfreigabe erfahren Sie unter: https://support.apple.com/HT201060."
                    + "Kauffreigabe: Die Kauffreigabe-Funktion innerhalb der Familienfreigabe ermöglicht das Teilen von dafür zugelassenen Inhalten mit bis zu sechs Familienmitgliedern. Der:Die Organisator:in lädt andere Mitglieder dazu ein teilzunehmen, und verpflichtet sich, die Kosten für jegliche durch Familienmitglieder eingeleitete Transaktionen zu tragen. Die gültigen Zahlungsmethoden des:der Organisator:in werden für die Zahlung aller Transaktionen genutzt, die von einem Familienmitglied initiiert werden (außer der Account des Familienmitglieds verfügt über ein Guthaben, welches stets zuerst verwendet wird). Familienmitglieder handeln als Vertreter:innen für den:die Organisator:in, wenn die gültigen Zahlungsmethoden des:der Organisator:in eingesetzt werden. Der:Die Organisator:in erklärt sich damit einverstanden, (1) diese Transaktionen zu bezahlen,(2) dass von Familienmitgliedern initiierte Transaktionen autorisiert sind und (3) dass Transaktionen mithilfe von gültigen Zahlungsmethoden durchgeführt werden, wie im obengenannten Abschnitt B beschrieben ist. Der:Die Organisator:in ist verantwortlich für die Einhaltung seines:ihres Zahlungsmittelvertrags und übernimmt alle Risiken, die mit der gemeinsamen Nutzung der gültigen Zahlungsmethode durch Familienmitglieder verbunden sind. Eine Quittung oder Rechnung für jede Transaktion eines Familienmitglieds wird an das die Transaktion initiierende Familienmitglied und, falls über die Zahlungsmethode des:der Organisator:in abgerechnet wurde, auch an den:die Organisator:in geschickt."
                    + "Kaufanfrage: „Kaufanfrage“ ist eine Funktion, die es einem:einer Organisator:in ermöglicht, von einem Familienmitglied unter 18 (oder dem entsprechenden Alter der Volljährigkeit in Ihrem Heimatland) initiierte Transaktionen zu genehmigen. Inhalte, die von Familienmitgliedern geteilt oder über Inhaltscodes erworben werden, unterliegen im Allgemeinen nicht der Kaufanfrage; Inhaltscodes, die den Zugang zu Abonnementsermöglichen, unterliegen der Kaufanfrage. Der:Die Organisator:in muss ein Elternteil oder ein:e Erziehungsberechtigte:r jedes Familienmitglieds sein, für das „Kaufanfrage“ aktiviert ist. Inhalte, die über den Account von Familienmitgliedern geteilt oder über Inhaltscodes erworben werden, unterliegen ggf. nicht der Funktion „Kaufanfrage“. Die Kaufanfrage ist standardmäßig für alle Familienmitglieder unter 13 Jahren (oder dem entsprechenden Mindestalter in Ihrem Heimatland) aktiviert und bleibt aktiviert, bis sie von den Eltern oder Erziehungsberechtigten deaktiviert wird. Wenn die Kaufanfrage deaktiviert wird nachdem das Familienmitglied 18 Jahre alt geworden ist, kann sie nicht mehr aktiviert werden. Die Kaufanfrage setzt nicht voraus, dass die Kauffreigabe aktiviert ist."
                    + "Änderungen von Familienmitgliedern: Wenn ein Familienmitglied die Familie verlässt oder aus der Familie entfernt wird, können die verbleibenden Familienmitglieder möglicherweise nicht mehr auf die Inhalte des früheren Familienmitglieds, einschließlich der mit der Zahlungsmethodel des:der Organisator:in erworbenen Inhalte, zugreifen."
                    + "Regeln für die Familienfreigabe: Sie können nur einer Familie zur gleichen Zeit angehören und höchstens zweimal im Jahr einer Familie beitreten. Sie können die Apple‑ID, die Sie mit einer Familie verknüpfen, höchstens einmal in 90 Tagen ändern. Alle Familienmitglieder müssen dasselbe Heimatland haben. Nicht alle Inhalte, einschließlich In-App-Käufe, Abonnements und bestimmte bereits erworbene Apps, stehen für die Kauffreigabe zur Verfügung. Abonnements von Apple TV+, Apple TV Channels, Apple One Family, Apple One Premier, Apple Music Family, Apple Arcade, Apple News+ und Apple Fitness+ sind automatisch für die Familienfreigabe aktiviert. Inhalte von Familienabonnements können Nutzungseinschränkungen per Abonnement unterliegen."
    },
    {
        "title": "E. STAFFELPASS UND MULTIPASS",
        "content": "Ein Pass ermöglicht es Ihnen, TV-Inhalte zu kaufen und zu erhalten, sobald diese zur Verfügung stehen. Ein Staffelpass gilt für TV-Inhalte, die eine begrenzte Anzahl von Folgen pro Staffel haben; ein Multipass gilt für TV-Inhalte, die laufend zur Verfügung stehen. Der volle Preis eines Staffelpasses bzw. Multipasses wird zum Zeitpunkt der Transaktion berechnet. Staffelpass- bzw. Multipass-Inhalte sind für bis zu 90 Tage, nachdem die letzte Folge zur Verfügung gestellt wurde, verfügbar zum Herunterladen. Wenn ein Anbieter von Inhalten weniger Folgen als bei Erwerb eines Staffelpasses geplant an Apple liefert, schreiben wir Ihrer Apple-ID den Einzelhandelswert der entsprechenden Anzahl von Folgen gut, die nicht an Apple geliefert wurden."
    },
    {
        "title": "F. ZUSÄTZLICHE BEDINGUNGEN FÜR DEN APP STORE (MIT AUSNAHME VON APPLE ARCADE-APPS)",
        "content": [
            {
                "title": "LIZENZ FÜR APP STORE-INHALTE",
                "content": "App-Lizenzen werden Ihnen von Apple oder einem Drittentwickler („App-Provider“) zur Verfügung gestellt. Apple agiert beim Betrieb des App Store als Vermittler für App-Provider und ist nicht Partei des Kaufvertrags oder der Nutzungsvereinbarung zwischen Ihnen und dem App-Provider. Wenn Sie jedoch Kunde von Apple Distribution International Ltd. sind, ist Apple Distribution International Ltd. der Vertragspartner, was bedeutet, dass Sie die App-Lizenz von Apple Distribution International Ltd. erwerben, die App jedoch vom App-Provider lizenziert wird. Eine von Apple lizenzierte App ist eine „Apple-App“; eine von einem App-Provider lizenzierte App ist eine „Dritt-App“.Jede App, die Sie erwerben, unterliegt dem nachstehenden Endbenutzer-Lizenzvertrag für Lizenzierte Applikationen („Standard-EULA“), es sei denn, Apple oder der App-Provider bietet einen vorrangigen individuellen Lizenzvertrag („Individuelle-EULA“) an. Der App-Provider einer Dritt-App ist allein verantwortlich für deren Inhalte, Gewährleistungen und für Ansprüche, die Sie ggf. in Bezug auf die Dritt-App vorbehaltlich lokaler Gesetze haben. Sie erkennen an und erklären sich damit einverstanden, dass Apple ein Drittbegünstigter unter der für die jeweilige Dritt-App geltenden Standard-EULA oder Individuellen-EULA ist und Apple daher einen solchen Vertrag durchsetzen kann. Bestimmte Apps, wie Stickers und iMessage-Apps, erscheinen möglicherweise nicht auf dem SpringBoard Ihres Geräts, können aber über den Nachrichten-App-Drawer aufgerufen und genutzt werden."
            },
            {
                "title": "IN-APP-KÄUFE",
                "content": "Apps können Inhalte, Dienste oder Funktionalitäten für die Nutzung innerhalb dieser Apps anbieten („In-App-Käufe“). In-App-Käufe, die während der Nutzung der App getätigt werden (z. B. virtuelle Edelsteine) können nicht zwischen Geräten ausgetauscht werden und können nur einmal heruntergeladen werden. Sie müssen Ihren Account – unabhängig von Authentifizierungen zum Erwerb anderer Inhalte – authentifizieren, bevor Sie In-App-Käufe tätigen, indem Sie Ihr Passwort eingeben oder Touch ID bzw. Face ID verwenden. Sie können für fünfzehn Minuten ohne erneute Authentifizierung weitere In-App-Käufe tätigen, es sei denn, Sie haben uns angewiesen, bei jedem Kauf ein Passwort zu verlangen oder Sie haben Touch ID bzw. Face ID aktiviert. Sie können die Möglichkeit, In-App-Käufe zu tätigen, nach folgender Anleitung deaktivieren: https://support.apple.com/HT201304."
            },
            {
                "title": "APP-BUNDLE",
                "content": "Einige Apps können gemeinsam als Paket verkauft werden („App-Bundle“). Der bei einem App-Bundle angezeigte Preis ist der Preis, der für den Erwerb des App-Bundles fällig wird. Der Preis für ein App-Bundle kann verringert werden, falls Sie bestimmte Apps bereits erworben haben. Zur Vervollständigung des App-Bundles kann jedoch eine Minimalgebühr anfallen."
            },
            {
                "title": "SUCHERGEBNISSE UND RANGLISTEN",
                "content": "Bei der Festlegung der Reihenfolge der Apps in den Suchergebnissen werden vor allem die von den App-Providern bereitgestellten Metadaten, die Art und Weise, wie Kunden die Apps und den App Storenutzen, sowie die Beliebtheit der Apps im App Store berücksichtigt. Diese Hauptparameter liefern die relevantesten Ergebnisse für die Suchanfragen der Kunden."
            },
            {
                "title": "ENDBENUTZER-LIZENZVERTRAG FÜR LIZENZIERTE APPLIKATIONEN",
                "content": "Die über den App Store zur Verfügung gestellten Apps werden an Sie lizenziert, nicht verkauft. Ihre Lizenz für die jeweilige App ist abhängig von Ihrer vorherigen Annahme entweder dieses Endbenutzer-Lizenzvertrages für Lizenzierte Applikationen („Standard-EULA“) oder eines individuellen Endbenutzer-Lizenzvertrages zwischen Ihnen und dem App-Provider („Individuelle-EULA“), sofern ein solcher bereitgestellt wird. Ihre Lizenz für eine Apple-App im Rahmen dieser Standard-EULA oder Individuellen-EULA wird von Apple eingeräumt, und Ihre Lizenz für eine Dritt-App im Rahmen dieser Standard-EULA oder Individuellen-EULA wird von dem App-Provider dieser Dritt-App eingeräumt. Jede App, die dieser Standard-EULA unterliegt, wird in diesem Vertrag als „Lizenzierte Applikation“ bezeichnet. Der App-Provider bzw. Apple („Lizenzgeber“) behält sich alle Rechte an der Lizenzierten Applikation vor, die Ihnen nicht ausdrücklich im Rahmen dieser Standard-EULA gewährt werden."
                    + "a. Umfang der Lizenz: Der Lizenzgeber räumt Ihnen eine nicht-übertragbare Lizenz zur Nutzung der Lizenzierten Applikation mit Apple-Markenprodukten, die sich in Ihrem Eigentum oder Besitz befinden, in dem nach den Nutzungsregeln zulässigen Umfang ein. Die Bedingungen dieser Standard-EULA gelten für alle Inhalte, Materialien oder Dienste, auf die von der Lizenzierten Applikation zugegriffen werden kann oder die innerhalb der Lizenzierten Applikation gekauft werden können, sowie für alle vom Lizenzgeber zur Verfügung gestellten Upgrades, welche die ursprüngliche Lizenzierte Applikation ersetzen oder ergänzen, sofern ein entsprechendes Upgrade nicht mit einer Individuellen-EULA einhergeht. Soweit nicht in den Nutzungsregeln angegeben, dürfen Sie die Lizenzierte Applikation nicht über ein Netzwerk vertreiben oder verfügbar machen, in dem sie von vielen verschiedenen Geräten gleichzeitig genutzt werden könnte. Soweit in dieser Vereinbarung nicht ausdrücklich zugelassen, dürfen Sie die Lizenzierte Applikation nicht übertragen, weitervertreiben oder unterlizenzieren, und wenn Sie Ihr Apple-Gerät an Dritte verkaufen, müssen Sie die Lizenzierte Applikation zuvor von dem Apple-Gerät entfernen. Sie dürfen die Lizenzierte Applikation, Updates oder Teile davon nicht vervielfältigen (außer soweit im Rahmen dieser Lizenz und den Nutzungsregeln gestattet) zurückentwickeln, disassemblieren, versuchen, ihren Quellcode abzuleiten, verändern oder davon abgeleitete Werke erstellen (außer sofern und nur soweit eine der vorstehenden Einschränkungen nach geltendem Recht untersagt ist oder soweit dies ggf. nach den für die Nutzung von Open-Source-Komponenten, die in die Lizenzierte Applikation integriert sind, geltenden Lizenzbedingungen gestattet ist)."
                    + "b. Einwilligung zur Nutzung von Daten: Sie erklären sich damit einverstanden, dass der Lizenzgeber technische Daten und zugehörige Informationen – insbesondere, aber nicht nur, technische Informationen über Ihr Gerät, System und Ihre Anwendungssoftware sowie Peripheriegeräte – erheben und nutzen darf, die in regelmäßigen Abständen erfasst werden, um die Bereitstellung von Software-Aktualisierungen, Produkt-Support und anderen im Zusammenhang mit der Lizenzierten Applikation gegenüber Ihnen erbrachten Dienstleistungen (soweit gegeben) zu erleichtern. Der Lizenzgeber darf diese Informationen, sofern diese Sie nicht persönlich identifizieren, nutzen, um seine Produkte zu verbessern oder Ihnen Dienstleistungen oder Technologien zur Verfügung zu stellen."
                    + "c. Kündigung. Diese Standard-EULA bleibt bis zu ihrer Kündigung durch Sie oder den Lizenzgeber wirksam. Ihre Rechte aus dieser Standard-EULA enden automatisch, wenn Sie ihre Bedingungen nicht einhalten."
                    + "d. Externe Dienste. Die Lizenzierte Applikation kann Zugriff auf Dienste und Websites des Lizenzgebers und/oder Dritter ermöglichen (zusammengefasst und jeweils einzeln „externe Dienste“). Sie erklären sich damit einverstanden, die externen Dienste auf eigenes Risiko zu nutzen. Der Lizenzgeber ist nicht verantwortlich, die Inhalte oder Richtigkeit externer Dienste von Dritten zu überprüfen oder zu bewerten, und ist nicht haftbar für externe Dienste Dritter. Daten, die in einer Lizenzierten Applikation oder einem externen Dienst angezeigt werden, insbesondere Finanz-, Gesundheits- und Standortinformationen, dienen lediglich allgemeinen Informationszwecken und werden nicht vom Lizenzgeber oder seinen Vertretern garantiert. Sie nutzen die externen Dienste nicht in einer Art und Weise, die nicht den Bedingungen dieser Standard-EULA entspricht oder die Rechte am geistigen Eigentum des Lizenzgebers oder Dritter verletzt. Sie erklären sich damit einverstanden, die externen Dienste nicht zu nutzen, um natürliche oder juristische Personen zu belästigen, zu missbrauchen, zu stalken, zu bedrohen oder zu diffamieren und dass der Lizenzgeber für eine solche Nutzung nicht verantwortlich ist. Externe Dienste stehen ggf. nicht in allen Sprachen oder nicht in Ihrem Heimatland zur Verfügung und sind für die Nutzung an einem bestimmten Ort möglicherweise nicht geeignet oder verfügbar. Soweit Sie sich entscheiden, entsprechende externe Dienste zu nutzen, sind Sie allein verantwortlich für die Einhaltung aller anwendbaren Gesetze. Der Lizenzgeber behält sich vor, Zugriffsverbote oder -beschränkungen im Hinblick auf Externe Dienste zu ändern, zu sperren, aufzuheben, zu deaktivieren oder einzuführen, jederzeit ohne Mitteilung und Haftung gegenüber Ihnen."
                    + "e. GEWÄHRLEISTUNG: Der Lizenzgeber wird die Lizenzierte Applikation mit angemessener Sorgfalt zur Verfügung stellen und angemessene Sorgfalt hinsichtlich der externen Dienste anwenden, welche mittels der Lizenzierten Applikation erbracht oder zur Verfügung gestellt werden. Gemäß lokalem Recht können Sie ein gesetzliches Gewährleistungsrecht für die gekaufte Lizenzierte Applikation für die Dauer von mindestens zwei Jahren und für In-App-Abonnements für die Dauer der Vertragslaufzeit haben. Der Lizenzgeber gibt keine sonstigen Versprechen oder Zusicherungen im Hinblick auf die externen Dienste ab und gewährleistet insbesondere nicht, dass:"
                    + "(i) Ihre Nutzung der externen Dienste ohne Unterbrechung oder fehlerfrei sein wird;"
                    + "(ii) die externen Dienste frei von Verlusten, Korruption, Angriffen, Viren, Eingriffen, Hacking oder anderen sicherheitsrelevanten Störungen sein werden, und der Lizenzgeber schließt jegliche Haftung in diesem Zusammenhang aus. Für das Backup Ihres Systems sind Sie verantwortlich, inklusive des Backups sämtlicher Lizenzierter Applikationen, welche auf Ihrem System gespeichert sind."
                    + "f. Haftungsbeschränkung"
                    + "(i) Soweit nicht unten (ii) eingreift, sind der Lizenzgeber, seine Direktor:innen, Manager:innen, Arbeitnehmer:innen, verbundenen Unternehmen, Bevollmächtigten, Auftragnehmer:innen, Auftraggeber:innen oder Lizenzgeber keinesfalls für Verluste oder Schäden haftbar, die durch den Lizenzgeber, seine Arbeitnehmer:innen oder Bevollmächtigten verursacht wurden, wenn:"
                    + "(1) keine rechtliche Sorgfaltspflicht verletzt wurde, die der Lizenzgeber oder ein:e Arbeitnehmer:in oder Bevollmächtigte:r des Lizenzgebers schuldet;"
                    + "(2) es sich nicht um eine vernünftigerweise vorhersehbare Folge einer solchen Verletzung handelt;"
                    + "(3) eine etwaige Steigerung des Verlustes oder Schadens auf einer Verletzung einer Bestimmung dieser Endnutzer-Lizenzvereinbarung („Vereinbarung“) durch Sie beruht;"
                    + "(4) es auf eine Entscheidung des Lizenzgebers zurückzuführen ist, Sie zu warnen, Ihren Zugriff auf die externen Dienste zu unterbinden oder zu beenden oder andere Maßnahmen während der Untersuchung von vermuteten Verletzungen zu ergreifen oder als Folge dessen, dass der Lizenzgeber zum Schluss kommt, dass eine Verletzung dieser Vereinbarung erfolgt ist;"
                    + "(5) es im Zusammenhang steht mit Einkommensverlust, Verlust von Geschäften oder entgangenem Gewinn oder mit Verlust oder Verfälschung von Daten im Zusammenhang mit Ihrer Nutzung der Lizenzierten Applikation."
                    + "(ii) Nichts in dieser Vereinbarung soll die Haftung des Lizenzgebers wegen Betrug, grober Fahrlässigkeit, vorsätzlichen Verhaltens, oder für Tod oder Körperverletzung aufgrund von Fahrlässigkeit des Lizenzgebers ausschließen oder begrenzen."
                    + "g. Sie dürfen die Lizenzierte Applikation nicht nutzen oder sonst wie exportieren oder re-exportieren, außer es ist von den Gesetzen der USA und den Gesetzen des Landes, in dem die Lizenzierte Applikation erworben wurde, erlaubt. Insbesondere darf die Lizenzierte Applikation nicht (a) in mit einem US-Embargo belegte Länder oder (b) an Personen, die auf der Specially Designated Nationals-Liste des U.S. Treasury Departments oder auf der Denied Persons-Liste oder der Denied Entity-Liste des U.S. Departement of Commerce stehen, exportiert oder re-exportiert werden. Mit der Nutzung der Lizenzierten Applikation sichern Sie zu und gewährleisten, dass Sie sich nicht in einem dieser Länder befinden und nicht auf einer dieser Listen stehen. Sie erklären sich auch damit einverstanden, dass Sie diese Produkte nicht für Zwecke nutzen, die nach dem Recht der USA verboten sind, insbesondere nicht, um Nuklearwaffen, Raketen, Chemie- oder Biowaffen zu entwickeln, zu entwerfen, herzustellen oder zu produzieren."
                    + "h. Endnutzer in der amerikanischen Regierung. Die Lizenzierte Applikation und damit im Zusammenhang stehende Dokumentation sind „Commercial Items“, wie in 48 C.F.R. §2.101 definiert, bestehend aus „Commercial Computer Software“ und „Commercial Computer Software Documentation“ in dem Sinne, in dem diese Begriffe in 48 C.F.R. §12.212 oder 48 C.F.R. §227.7202, sofern anwendbar, verwendet werden. Im Einklang mit 48 C.F.R. §12.212. oder 48 C.F.R. §227.7202-1 bis 227.7202-4, sofern anwendbar, werden Commercial Computer Software und Commercial Computer Software Documentation an Endbenutzer der U.S. Behörden (a) nur als Commercial Items und (b) nur mit den Rechten, die auch allen anderen Endbenutzern entsprechend dieser Bedingungen eingeräumt werden, lizenziert. Unveröffentlichte Rechte unter den Urhebergesetzen von den USA werden vorbehalten."
                    + "i. Außer soweit ausdrücklich in dem folgenden Absatz vorgesehen, unterliegen dieser Vertrag und die Beziehung zwischen Ihnen und Apple den Gesetzen des U.S.-Bundesstaates Kalifornien, mit der Ausnahme der kalifornischen Gesetze, die sich mit dem Kollisionsrecht befassen. Sie und Apple erklären sich damit einverstanden, sich der persönlichen und ausschließlichen Zuständigkeit der Gerichte, die sich im County Santa Clara, Kalifornien befinden, zu unterwerfen, um jede Streitigkeit oder Klage, die sich aus diesem Vertrag ergibt, beizulegen. Wenn Sie (a) kein:e U.S.-Staatsangehörige:r sind; (b) Sie nicht in den USA wohnen; (c) Sie auf den Dienst nicht aus den USA zugreifen; und (d) Sie ein:e Staatsangehöriger:in eines der unten angegebenen Länder sind, erklären Sie sich hiermit einverstanden, dass jede Streitigkeit oder Klage, die sich aus diesem Vertrag ergibt, dem anwendbaren Recht, wie unten angegeben, unterliegt, ohne Rücksicht auf die Gesetze, die sich mit dem Kollisionsrecht befassen, und Sie unterwerfen sich hiermit unwiderruflich der nicht ausschließlichen Zuständigkeit der Gerichte, die sich in dem Bundesstaat, in der Provinz oder in dem Land, wie unten angegeben, befinden, dessen Recht gilt:"
                    + "Wenn Sie ein:e Bewohner:in eines Landes der Europäischen Union, Großbritanniens, der Schweiz, Norwegens oder Islands sind, sind das anwendbare Recht und der Gerichtsstand das Recht und die Gerichte Ihres gewöhnlichen Aufenthaltsortes."
                    + "Speziell ausgenommen von der Anwendbarkeit auf diesen Vertrag ist das UN-Kaufrecht."
            
            }
        ]
    }, 
    {
        "title": "G. ZUSÄTZLICHE BEDINGUNGEN FÜR VON DRITTPARTEIEN ERWORBENE INHALTE",
        "content": "Sie erwerben einige Inhalte, die in Apple Books, App Store und Apple Podcasts (inklusive Apple Podcast Abonnements) verfügbar sind, von dem Drittanbieter solcher Inhalte (wie auf der Produktseite und/oder während des Erwerbsvorgangs für die relevanten Inhalte angezeigt), nicht von Apple. In einem solchen Fall handelt Apple als ein Vertreter für den Anbieter der Inhalte, indem Apple Ihnen die Inhalte zur Verfügung stellt, und deshalb ist Apple keine Partei der Transaktion zwischen Ihnen und dem Anbieter der Inhalte. Wenn Sie jedoch ein Kunde von Apple Distribution International Ltd. sind, ist der Vertragspartner Apple Distribution International Ltd. für die Inhalte, die Sie erwerben, die Inhalte werden aber von dem Anbieter der Inhalte lizenziert. Der Anbieter der Inhalte behält sich das Recht vor, die auf diese Inhalte bezogenen Nutzungsbedingungen durchzusetzen. Der Anbieter der Inhalte ist allein verantwortlich für solche Inhalte, für alle Gewährleistungen, soweit diese nicht ausgeschlossen wurden, und für alle Ansprüche, die Sie oder eine andere Partei in Bezug auf solche Inhalte haben könnten."
    },
    {
        "title": "H. ZUSÄTZLICHE BEDINGUNGEN FÜR APPLE MUSIC",
        "content": "Die iCloud Music-Mediathek ist eine Apple Music-Funktion, die es Ihnen erlaubt, auf Ihre abgeglichenen oder hochgeladenen Songs, Playlisten und Musikvideos, die von Apple Music, dem iTunes Store oder einer anderen Quelle erworben wurden („iCloud Music- Mediathekinhalte“) auf Ihren Apple Music-fähigen Geräten zuzugreifen. Die iCloud Music-Mediathek wird automatisch eingeschaltet, wenn Sie Ihre Apple Music-Mitgliedschaft einrichten. Die iCloud Music-Mediathek erhebt Informationen über Ihre iCloud Music- Mediathekinhalte. Diese Informationen werden mit Ihrer Apple-ID verbunden und mit den auf Apple Music derzeit verfügbaren iCloud Music-Mediathekinhalten verglichen. Die iCloud Music- Mediathekinhalte, die nicht abgeglichen werden, werden auf die iCloud Music-Mediathek -Server von Apple hochgeladen (in einem von Apple festgelegten Format). Sie können bis zu 100.000 Songs hochladen. Songs, die von dem iTunes Store erworben wurden, zählen bei dieser Grenze nicht mit. Songs, die bestimmte Kriterien nicht erfüllen (z. B. übermäßig große Dateien) oder die für Ihr Gerät nicht zugelassen sind, sind für die iCloud Music-Mediathek nicht zugelassen. Wenn Sie die iCloud Music- Mediathek nutzen, erhebt Apple Informationen wie etwa die Stücke, die Sie abspielen, stoppen oder überspringen, die Geräte, die Sie verwenden und die Zeit und Dauer der Wiedergabe. Sie erklären sich damit einverstanden, die iCloud Music-Mediathek nur für rechtmäßig erworbene Inhalte zu nutzen. Die iCloud Music-Mediathek wird auf einer „wie gesehen“-Grundlage zur Verfügung gestellt und kann Fehler oder Ungenauigkeiten enthalten. Sie sollten Ihre Daten und Informationen sichern, bevor Sie die iCloud Music-Mediathek nutzen. Wenn Sie kein Apple Music-Mitglied sind, können Sie ein iTunes Match-Abonnement erwerben, das die iCloud Music-Mediathek verwendet. Wenn Ihre Mitgliedschaft bei Apple Music endet, verlieren Sie den Zugriff auf Ihre iCloud Music-Mediathek, einschließlich dem Inhalt der iCloud Music- Mediathek, der auf Server der iCloud Music-Mediathek hochgeladen ist."
    },
    {
        "title": "I. ZUSÄTZLICHE BEDINGUNGEN FÜR APPLE FITNESS+",
        "content": "Apple Fitness+ dient ausschließlich Unterhaltungs- und/oder Informationszwecken und ist nicht dazu gedacht, medizinischen Rat bereitzustellen. Sie sollten in Bezug auf (a) die Sicherheit und Ratsamkeit einer gegebenen Aktivität oder (b) spezifische medizinische Zustände oder Symptome stets einen qualifizierten Arzt aufsuchen."
    },
    {
        "title": "J. ANBIETER-MITGLIEDSCHAFT",
        "content": "Wenn verfügbar, kann Ihnen angeboten werden, eine Mitgliedschaft zur Nutzung eines Dienstes von Ihrem Mobilfunkanbieter (eine „Anbieter-Mitgliedschaft“) zu erwerben. Wenn Sie eine Anbieter-Mitgliedschaft erwerben, ist Ihr Mobilfunkanbieter („Anbieter“) der Vertragspartner, was bedeutet, dass Sie die Anbieter-Mitgliedschaft von Ihrem Anbieter erwerben, der Ihnen die Kosten dafür in Rechnung stellen wird, der Dienst jedoch von Apple lizenziert und bereitgestellt wird. Ihre Vertragsbeziehung mit dem Anbieter unterliegt den Bedingungen des Anbieters, nicht dieser Vereinbarung, und Abrechnungsstreitigkeiten in Bezug auf eine Anbieter-Mitgliedschaft sind an Ihren Anbieter zu richten, nicht an Apple. Indem Sie einen Dienst über eine Anbieter-Mitgliedschaft nutzen, stimmen Sie zu, dass Ihr Anbieter Ihre Anbieter-Account-Informationen, Telefonnummer und Abonnementinformationen mit Apple austauschen kann und dass Apple diese Informationen verwenden kann, um den Status Ihrer Anbieter-Mitgliedschaft zu bestimmen."
    },
    {
        "title": "K. VERSCHIEDENE BEDINGUNGEN FÜR ALLE DIENSTE",
        "content": [
            {
                "title": "DEFINITION VON APPLE",
                "content": "Abhängig von Ihrem Heimatland bedeutet „Apple“:+ "
                    + "Apple Inc., mit Sitz in One Apple Park Way, Cupertino, Kalifornien, USA für Benutzer:innen in den Vereinigten Staaten, darunter Puerto Rico;"
                    + "Apple Canada Inc., mit Sitz in 120 Bremner Blvd., Suite 1600, Toronto ON M5J 0A8, Kanada für Benutzer:innen in Kanada;"
                    + "Apple Services LATAM LLC, mit Sitz in 1 Alhambra Plaza, Ste 700 Coral Gables, Florida, für Benutzer in Mexiko, Mittel- oder Südamerika oder einem karibischen Land oder Territorium (außer Puerto Rico);"
                    + "iTunes K.K., mit Sitz in Roppongi Hills, 6-10-1 Roppongi, Minato-ku, Tokyo 106-6140, Tokyo, Japan für Benutzer:innen in Japan;"
                    + "Apple Pty Limited, mit Sitz in Level 3, 20 Martin Place, Sydney NSW 2000, Australien für Benutzer:innen in Australien oder Neuseeland einschließlich in einem ihrer Territorien oder verbundenen Jurisdiktionen; und"
                    + "Apple Distribution International Ltd., mit Sitz in Hollyhill Industrial Estate, Hollyhill, Cork, Republic of Ireland, für alle anderen Benutzer:innen."
            },
            {
                "title": "ÄNDERUNGEN DER VEREINBARUNG",
                "content": "Apple behält sich das Recht vor, diese Vereinbarung zu ändern und neue oder zusätzliche Bedingungen hinzuzufügen, was z.B. erforderlich sein kann, wenn Apple einen neuen Dienst hinzufügt oder sich das geltende Recht ändert. Diese Änderungen und zusätzlichen Bedingungen werden Ihnen mitgeteilt und sind, wenn sie akzeptiert werden, sofort wirksam und werden in diese Vereinbarung aufgenommen. Sofern Sie diese Änderungen nicht akzeptieren, hat Apple das Recht, die Vereinbarung zu kündigen, und/oder Sie sind möglicherweise nicht in der Lage, zukünftige Käufe im Zusammenhang mit Diensten oder Inhalten, die dieser Vereinbarung unterliegen, zu tätigen. Dies hat keine Auswirkungen auf die von Ihnen bereits erworbenen und heruntergeladenen Inhalte."
            },  
            {
                "title": "MATERIALIEN DRITTER",
                "content": "Apple ist nicht verantwortlich oder haftbar für Materialien Dritter, die in den Inhalten oder in den Diensten enthalten oder in diesen verlinkt sind."
            },
            {
                "title": "GEISTIGES EIGENTUM",
                "content": "Sie erklären sich damit einverstanden, dass die Dienste, insbesondere Inhalte, Grafiken, Benutzeroberfläche, Audio-Clips, Video-Clips, redaktionelle Inhalte sowie die Skripte und Software, die genutzt werden, um die Dienste zu implementieren, proprietäre Informationen und Materialien enthalten, die das Eigentum von Apple, seinen Lizenzgebern und/oder Inhalteanbietern sind, und diese vom anwendbaren Recht zum Schutze des geistigen Eigentums und anderen Gesetzen, insbesondere Urheberrechtsgesetze, geschützt sind. Sie erklären sich damit einverstanden, dass Sie diese proprietären Informationen oder Materialien nicht in irgendeiner Weise nutzen werden, mit Ausnahme der Nutzung der Dienste für persönliche, nichtkommerzielle Nutzungen in Übereinstimmung mit dieser Vereinbarung. Kein Teil der Inhalte oder Dienste darf in irgendeiner Form oder mit irgendwelchen Mitteln übertragen oder reproduziert werden, es sei denn, wie nach dieser Vereinbarung ausdrücklich erlaubt. Sie erklären sich damit einverstanden, die Dienste oder die Inhalte nicht in irgendeiner Art und Weise zu modifizieren, vermieten, verleihen, verkaufen, teilen oder zu verbreiten und Sie werden die Dienste nicht in irgendeiner Weise, die nicht ausdrücklich erlaubt ist, nutzen."
                    + "Der Name Apple, das Apple Logo, iTunes, iTunes Store, App Store, Apple Books, Apple Music, Apple TV, Apple TV+, Apple Arcade, Apple News, Apple News+, Apple One, Apple Podcasts, Apple Fitness+ und andere Markenzeichen, Dienstleistungsmarken, Grafiken und Logos von Apple, die in Verbindung mit den Diensten genutzt werden, sind Markenzeichen oder registrierte Markenzeichen von Apple in den USA und anderen Ländern der Welt. In Bezug auf alle vorgenannten Markenzeichen wird Ihnen weder ein Recht noch eine Lizenz eingeräumt."
            },
            {
                "title": "URHEBERRECHT",
                "content": "Sofern nicht anders angegeben, gehören von Apple bereitgestellte Dienste und Inhalte urheberrechtlich zu Apple Inc. und ihren Tochtergesellschaften."
                    + "Wenn Sie glauben, dass Inhalte, die durch die Dienste verfügbar sind, Ihr Urheberrecht verletzt, kontaktieren Sie bitte Apple unter den folgendenAdressen:"
                    + "- Apps von Dritten: https://www.apple.com/legal/internet-services/itunes/appstorenotices/"
                    + "- Apple Books: https://www.apple.com/legal/internet-services/itunes/applebooksnotices/"
                    + "- Apple TV+ und Apple Fitness+: https://www.apple.com/legal/internet-services/itunes/appletvplusnotices"
                    + "- Apple News: https://www.apple.com/legal/internet-services/itunes/applenewsnotices"
                    + "- Klingeltöne: https://www.apple.com/legal/internet-services/itunes/ringtonestorenotices/"
                    + "- alle anderen Dienste (darunter unter anderem iTunes Store, Apple Music und Apple Podcasts): https://www.apple.com/legal/internet-services/itunes/itunesstorenotices/"
                    + "Dies ist der schnellste Weg für uns, Ihre Meldung einer behaupteten Rechtsverletzung zu bearbeiten. Die langsamere Methode, um unseren Beauftragten zu erreichen und Ihre Meldung zu bearbeiten, besteht darin, eine ordnungsgemäße und vollständige Meldung der behaupteten Rechtsverletzung an die unten angegebene Postanschrift zu senden."
                    + "Apple Inc."
                    + "Attn: Copyright Agent"
                    + "Ein Apple Park Way"
                    + "MS: 1IPL"
                    + "Cupertino, CA 95014"
                    + "Telefon: 408.996.1010"
                    + "E-Mail: copyrightnotices@apple.com"
                    + "Apple hat eine Richtlinie eingeführt, um die Konten von Nutzern, die wiederholt die Urheberrechte anderer verletzen oder von denen wiederholt behauptet wird, dass sie die Urheberrechte anderer verletzen, unter angemessenen Umständen zu deaktivieren und/oder zu kündigen. Im Rahmen der Umsetzung dieser Politik kann Apple nach eigenem Ermessen die Konten von Nutzern aussetzen, deaktivieren und/oder auflösen, die wiederholt in rechtsverletzende Aktivitäten verwickelt sind, oder aus anderen damit verbundenen Gründen."  
            },
            {
                "title": "BEENDIGUNG UND SPERRUNG VON DIENSTEN",
                "content": "Bei Verletzung der Bestimmungen dieser Vereinbarung ist Apple berechtigt: (i) diese Vereinbarung und/oder Ihre Apple ID zu kündigen, wobei Sie für alle unter Ihrer Apple ID fälligen Beträge bis einschließlich des Kündigungsdatums haftbar bleiben; und/oder (ii) Ihre Lizenz für die Software zu kündigen; und/oder (iii) Ihren Zugang zu den Diensten auszuschließen."
                    + "Apple behält sich ferner das Recht vor, die Dienste (oder Teile oder Inhalte davon) jederzeit aus technischen oder betrieblichen Gründen zu ändern, auszusetzen oder einzustellen, und Apple haftet weder Ihnen noch Dritten gegenüber, wenn es von diesen Rechten Gebrauch macht. Soweit möglich, wird Apple Sie im Voraus über jede Änderung, Aussetzung oder Einstellung der Dienste informieren. Die Beendigung des Dienstes hat keine Auswirkungen auf die Inhalte, die Sie bereits erworben und heruntergeladen haben. Allerdings kann es sein, dass Sie zusätzliche Computer nicht mehr für die Nutzung dieser Inhalte freigeben können. Wenn Apple einen Dienst einstellt, für den Sie bereits ein Abonnement bezahlt haben, erhalten Sie von Apple eine Rückerstattung."
            },
            {
                "title": "GEWÄHRLEISTUNGSAUSSCHLUSS; HAFTUNGSBESCHRÄNKUNGEN",
                "content": "a. Apple erbringt die Dienste mit angemessener Sorgfalt Gemäß lokalem Recht können Sie ein gesetzliches Gewährleistungsrecht für gekaufte Inhalte für die Dauer von mindestens zwei Jahren und für Abonnements für die Dauer der Vertragslaufzeit haben. Apple gibt keine sonstigen Versprechen oder Zusicherungen im Hinblick auf die Dienste und gewährleistet insbesondere nicht, dass über die gesetzliche Gewährleistung hinaus:"
                    + "(i) Ihre Nutzung der externen Dienste ohne Unterbrechungen oder fehlerfrei sein wird. Sie erklären sich damit einverstanden, dass Apple die Dienste ggf. aus technischen oder betrieblichen Gründen auf unbestimmte Zeit aussetzen oder jederzeit einstellen kann und Sie, soweit möglich, darüber informiert. Wenn Apple einen Dienst einstellt, für den Sie bereits ein Abonnement bezahlt haben, wird Apple Ihnen eine Rückerstattung gewähren. Wenn Apple einen Dienst einstellt, bei dem es sich nicht um ein Abonnement handelt, hat dies keine Auswirkungen auf die Inhalte, die Sie bereits erworben und heruntergeladen haben;"
                    + "(ii) die Dienste frei von Verlusten, Korruption, Angriffen, Viren, Eingriffen, Hacking oder anderen sicherheitsrelevanten Störungen sein werden, die als Fälle höherer Gewalt gelten. Apple schließt jegliche Haftung in diesem Zusammenhang aus. Sie sind für die Sicherung Ihres Systems verantwortlich, einschließlich der Sicherung aller Inhalte, die Sie über den Dienst gekauftoder erworben haben."
                    + "b. SIE ERKLÄREN SICH DAMIT EINVERSTANDEN, DASS, SOFERN GESETZLICH NICHT ANDERS VORGESCHRIEBEN, APPLE NICHT DAFÜR VERANTWORTLICH IST, IHNEN WEITERHIN INHALTE ÜBER UNSERE DIENSTE ZUR VERFÜGUNG ZU STELLEN, UND DASS APPLE IHNEN GEGENÜBER NICHT HAFTBAR IST, WENN INHALTE, EINSCHLIESSLICH GEKAUFTER INHALTE, NICHT MEHR ZUM HERUNTERLADEN ODER ERNEUTEN HERUNTERLADEN ZUR VERFÜGUNG STEHEN."
                    + "c. Soweit nicht unten (e) eingreift oder Sie die Ihnen durch die anwendbaren Gesetze zustehenden Rechte zur Kaufpreisrückerstattung oder zum Schadenersatz ausüben, sind Apple, seine Direktor:innen, Manager:innen, Arbeitnehmer:innen, verbundenen Unternehmen, Bevollmächtigten, Auftragnehmer oder Lizenzgeber keinesfalls für Verluste oder Schäden haftbar, die durch Apple, seine Arbeitnehmer:innen oder Bevollmächtigten verursacht wurden, wenn:"
                    + "(i) keine rechtliche Sorgfaltspflicht verletzt wurde, die Apple oder ein:e Arbeitnehmer:in oder Bevollmächtigte:r von Apple obliegt;"
                    + "(ii) es sich nicht um eine vernünftigerweise vorhersehbare Folge einer solchen Verletzung handelt;"
                    + "(iii) eine etwaige Steigerung des Verlustes oder Schadens auf einer Verletzung einer Bestimmung dieser Vereinbarung durch Sie beruht;"
                    + "(iv) es auf eine Entscheidung von Apple zurückzuführen ist, Informationen oder Inhalte zu entfernen oder den Zugriff auf diese zu verweigern, Ihren Zugriff auf die Dienste zu suspendieren oder zu beenden oder andere Maßnahmen während der Untersuchung eines mutmaßlichen Verstoßes oder als Ergebnis von Apples Schlussfolgerung dass ein Verstoß gegen diese Vereinbarung stattgefunden hat, zu ergreifen; oder"
                    + "(v) es im Zusammenhang steht mit Einkommensverlust, Verlust von Geschäften oder entgangenem Gewinn oder mit Verlust oder Beschädigung von Daten im Zusammenhang mit Ihrer Nutzung der Dienste."
                    + "d. Apple ergreift angemessene Maßnahmen, um die von Ihnen im Zusammenhang mit den Diensten bereitgestellten Informationen zu schützen, einschließlich vor einer Nutzung mit betrügerischen Absichten."
                    + "e. Nichts in dieser Vereinbarung soll die Haftung von Apple wegen grober Fahrlässigkeit, vorsätzlichen Verhaltens, Betrugs, oder für Tod oder Körperverletzung ausschließen oder begrenzen."
                    + "f. Wenn Sie diese Vereinbarung verletzen, sind Sie Apple, seinen Direktor:innen, Manager:innen, Arbeitnehmer:innen, verbundenen Unternehmen, Bevollmächtigten, Auftragnehmern und Lizenzgebern für jeden Anspruch, der aus Ihrer Verletzung herrührt, haftbar. Sie sind außerdem für alle Maßnahmen verantwortlich, die von Apple als Teil der Untersuchung einer vermuteten Verletzung dieser Vereinbarung oder als Folge der Untersuchungsergebnisse oder der Entscheidung, dass eine Verletzung dieser Vereinbarung stattgefunden hat, ergriffen werden."
                    + "g. APPLE IST NICHT FÜR DATENGEBÜHREN VERANTWORTLICH, DIE IN VERBINDUNG MIT IHRER NUTZUNG DER DIENSTE ENTSTEHEN KÖNNEN."
            }, 
            {
                "title": "GESETZLICHE AUSNAHMEN FÜR ÖFFENTLICHE EINRICHTUNGEN",
                "content": "Wenn Sie eine qualifizierte öffentliche Bildungseinrichtung oder staatliche Einrichtung sind und ein Teil dieser Vereinbarung, zum Beispiel der Abschnitt zur Haftungsfreistellung in Gänze oder in Teilen, Ihnen gegenüber aufgrund von anwendbarem lokalen, nationalen, Landes- oder Bundesrecht ungültig oder nicht durchsetzbar ist, dann soll dieser Teil ggf. als ungültig oder nicht durchsetzbar gelten und stattdessen in einer Art und Weise ausgelegt werden, die am ehesten mit dem anwendbaren Recht vereinbar ist."
            }, 
            {
                "title": "ANWENDBARES RECHT",
                "content": "Sofern nachfolgend nicht anderweitig geregelt oder durch geltendes Recht anderweitig vorgeschrieben, unterliegt diese Vereinbarung und die Beziehung zwischen Ihnen und Apple sowie alle Transaktionen über die Dienste den Gesetzen des U.S.-Bundesstaates Kalifornien, mit der Ausnahme der kalifornischen Gesetze, die sich mit dem Kollisionsrecht befassen. Sie und Apple erklären sich damit einverstanden, sich der persönlichen und ausschließlichen Zuständigkeit der Gerichte, die sich im County Santa Clara, Kalifornien befinden, zu unterwerfen, um jede Streitigkeit oder Klage, die sich aus dieser Vereinbarung ergibt, beizulegen. Wenn Sie (a) kein:e U.S.-Staatsangehörige:r sind; (b) Sie nicht in den USA wohnen; (c) Sie auf den Dienst nicht aus den USA zugreifen; und (d) Sie ein:e Staatsangehörige:r eines der unten angegebenen Länder sind, erklären Sie sich hiermit einverstanden, dass jede Streitigkeit oder Klage, die sich aus dieser Vereinbarung ergibt, dem anwendbaren Recht, wie unten angegeben, unterliegt, ohne Rücksicht auf die Gesetze, die sich mit dem Kollisionsrecht befassen, und Sie unterwerfen sich hiermit unwiderruflich der nicht ausschließlichen Zuständigkeit der Gerichte, die sich in dem Bundesstaat, in der Provinz oder in dem Land, wie unten angegeben, befinden, dessen Recht gilt:"
                    + "Wenn Sie ein:e Bewohner:in eines Landes der Europäischen Union, Großbritanniens, der Schweiz, Norwegens oder Islands sind, sind das anwendbare Recht und der Gerichtsstand das Recht und die Gerichte Ihres gewöhnlichen Aufenthaltsortes."
                    + "Speziell ausgenommen von der Anwendbarkeit auf diese Vereinbarung ist das UN-Kaufrecht."
            },
            {
                "title": "WEITERE BESTIMMUNGEN",
                "content": "Diese Vereinbarung stellt die gesamte Vereinbarung zwischen Ihnen und Apple dar und regelt Ihre Nutzung der Dienste und ersetzt dabei etwaige frühere Vereinbarungen zwischen Ihnen und Apple in Bezug auf den gleichen Gegenstand. Sie können auch zusätzlichen Bedingungen unterliegen, die gelten können, wenn Sie Transaktionen durchführen oder Partnerdienste, Inhalte Dritter, Software Dritter oder zusätzliche Dienste, wie etwa das Programm für Volumenlizenzen (VPP), nutzen. Sollte eine oder mehrere Bestimmungen dieser Vereinbarung im Ganzen oder in Teilen ungültig oder nicht durchsetzbar sein oder werden, soll(en) diese Bestimmung(en) stattdessen in einer Art und Weise ausgelegt werden, die mit dem anwendbaren Recht vereinbar ist, um die ursprünglichen Intentionen der Parteien so genau wie möglich widerzuspiegeln und dabei nicht die Gültigkeit und Durchsetzbarkeit der verbleibenden Bestimmungen dieser Vereinbarung berühren. Das Unterlassen von Apple, ein Recht oder Bestimmungen aus dieser Vereinbarung durchzusetzen, begründet keinen Verzicht auf dieses Recht oder diese oder andere Bestimmung(en). Apple ist nicht verantwortlich für die Nichterfüllung von Pflichten aus Gründen, die außerhalb der Kontrolle von Apple liegen."
                    + "Sie erklären sich damit einverstanden, alle lokalen, staatlichen, bundesstaatlichenund nationalen Gesetze, Statuten, Verordnungen und Vorschriften einzuhalten, die auf Ihre Nutzung der Dienste Anwendung finden. Ihre Nutzung der Dienste kann auch anderen Gesetzen unterliegen. Das Risiko des Verlustes für alle elektronisch übermittelten Transaktionen geht auf den Erwerber mit der elektronischen Übermittlung an den Empfänger über. Kein:e Angestellte:r oder Vertreter:in von Apple ist berechtigt, diese Vereinbarung zu ändern."
                    + "Apple kann Sie bezüglich der Dienste durch Versand einer E-Mail-Nachricht an Ihre E-Mail-Adresse oder eines Briefes an Ihre Postadresse oder durch eine Bekanntmachung in den Diensten benachrichtigen. Die Benachrichtigung wird sofort wirksam. Apple kann Sie auch per E-Mail oder Push-Benachrichtigung kontaktieren, um Ihnen zusätzliche Informationen über die Dienste zu senden."
                    + "Alternative Streitbeilegung. Die EU betreibt eine freiwillige Online-Streitbeilegungsplattform, die über den folgenden Link erreichbar ist: https://ec.europa.eu/consumers/odr, bezüglich derer sich Apple Distribution International Ltd. entschieden hat, nicht teilzunehmen. Sollten Sie ein Problem feststellen, kontaktieren Sie den iTunes Support https://www.apple.com/support/itunes/contact."
                    + "Sie räumen Apple hiermit das Recht ein, Schritte zu unternehmen, die Apple als vernünftigerweise erforderlich oder angemessen ansieht, um die Einhaltung einer oder mehrerer Bestimmungen dieser Vereinbarung durchzusetzen und/oder zu verifizieren. Sie stimmen zu, dass Apple das Recht hat, in dem Rahmen, in dem Apple es für vernünftigerweise erforderlich und angemessen hält, ohne Haftung Ihnen gegenüber, jegliche Daten und/oder Informationen an Strafverfolgungsbehörden, Regierungsvertreter:innen und/oder Drittparteien weiterzugeben, um die Einhaltung einer oder mehrerer Bestimmungen dieser Vereinbarung durchzusetzen und/oder zu verifizieren ( einschließlich, aber nicht beschränkt auf das Recht von Apple, bei rechtlichen Verfahren in Bezug auf Ihre Nutzung der Dienste und/oder Inhalte und/oder einer Behauptung einer Drittpartei, dass Ihre Nutzung der Dienste und/oder Inhalte rechtswidrig ist und/oder die Rechte der Drittpartei verletzt, zu kooperieren)."
                    + "Zustellungsbevollmächtigte. Für behördliche Zustellungen an Medienintermediäre des Apple Konzerns gemäß § 2 Absatz 2 Nr. 16 Medienstaatsvertrag sind als inländische Zustellungsbevollmächtigte nach § 92 Medienstaatsvertrag SKW Schwarz Rechtsanwälte, Wittelsbacher Platz 1, 80333 München in anwaltlicher Vertretung benannt. Diese Zustellungsbevollmächtigung bezieht sich ausschließlich auf behördliche Zustellungen. Zivilrechtliche oder sonstige Eingaben werden nicht bearbeitet."
                
            }
        ]
    }















]